### ISSUE TITLE
r18开启指令相关

### ISSUE THREAD

**Issue by LaoLittle** [JOYACEpoor/miraisetuplugin#2]
或许可以把权限移交至mirai-console管理，或者说是单独开一个指令可以任意添加删除r18管理员

还有就是readme里写的`本插件不需要额外配置`或许不那么准确了

**Comment by JOYACEpoor** [comment]
readme还没改

我姐的miraiconsole自带的权限管理非常滴难用（

**Comment by LaoLittle** [comment]
> 

搞个添加指令嘛，比如/r18 add+q号
就把他加入，这样
